server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/e-learning?createDatabaseIfNotExist=true
      username: trantor
      password: trantor
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQLDialect
